/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.domain.Boleta;
import com.incloud.hcp.domain.response.BoletaResponse;
import com.incloud.hcp.repository.delta.BoletaDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import org.springframework.beans.factory.annotation.Autowired;

public abstract class BoletaRest extends JPACustomRest<BoletaResponse, Boleta, Integer> {

    @Autowired
    protected BoletaDeltaRepository boletaDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "Boleta";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final Boleta createInstance() {
        Boleta boleta = new Boleta();
        return boleta;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
