/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.domain.Prueba;
import com.incloud.hcp.domain.response.PruebaResponse;
import com.incloud.hcp.repository.delta.PruebaDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import org.springframework.beans.factory.annotation.Autowired;

public abstract class PruebaRest extends JPACustomRest<PruebaResponse, Prueba, Long> {

    @Autowired
    protected PruebaDeltaRepository pruebaDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "Prueba";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final Prueba createInstance() {
        Prueba prueba = new Prueba();
        return prueba;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
