/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.google.common.base.MoreObjects;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "BOLETA")
//@Audited
//@AuditTable("_audi_BOLETA")
public class Boleta extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(Boleta.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Integer id;
    private String descripcion;
    private String fecha;

    @Override
    public String entityClassName() {
        return Boleta.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "ID", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_BOLETA")
    @Id
    @SequenceGenerator(name = "seq_BOLETA", sequenceName = "seq_BOLETA", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Boleta id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [descripcion] ------------------------

    @NotEmpty(message = "{message.boleta.descripcion.requerido}")
    @Size(max = 200, message = "{message.boleta.descripcion.sizeMax} {max} {message.caracter}")
    @Column(name = "DESCRIPCION", nullable = false, length = 200)
    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Boleta descripcion(String descripcion) {
        setDescripcion(descripcion);
        return this;
    }
    // -- [fecha] ------------------------

    @NotEmpty(message = "{message.boleta.fecha.requerido}")
    @Size(max = 20, message = "{message.boleta.fecha.sizeMax} {max} {message.caracter}")
    @Column(name = "FECHA", nullable = false, length = 20)
    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public Boleta fecha(String fecha) {
        setFecha(fecha);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Boleta withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Boleta && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Boleta instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("descripcion", getDescripcion()) //
                .add("fecha", getFecha()) //
                .toString();
    }
}
