/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.google.common.base.MoreObjects;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "ITEM")
//@Audited
//@AuditTable("_audi_ITEM")
public class Item extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(Item.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Integer id;
    private String descripcion;
    private Integer stock;

    // Many to one
    private Boleta idBoleta;

    @Override
    public String entityClassName() {
        return Item.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "ID", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_ITEM")
    @Id
    @SequenceGenerator(name = "seq_ITEM", sequenceName = "seq_ITEM", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Item id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [descripcion] ------------------------

    @NotEmpty(message = "{message.item.descripcion.requerido}")
    @Size(max = 255, message = "{message.item.descripcion.sizeMax} {max} {message.caracter}")
    @Column(name = "DESCRIPCION", nullable = false)
    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Item descripcion(String descripcion) {
        setDescripcion(descripcion);
        return this;
    }
    // -- [stock] ------------------------

    @Digits(integer = 10, fraction = 0)
    @NotNull
    @Column(name = "STOCK", nullable = false, precision = 10)
    public Integer getStock() {
        return stock;
    }

    public void setStock(Integer stock) {
        this.stock = stock;
    }

    public Item stock(Integer stock) {
        setStock(stock);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Item.idBoleta ==> Boleta.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "ID_BOLETA", nullable = false)
    @ManyToOne
    public Boleta getIdBoleta() {
        return idBoleta;
    }

    /**
     * Set the {@link #idBoleta} without adding this Item instance on the passed {@link #idBoleta}
     */
    public void setIdBoleta(Boleta idBoleta) {
        this.idBoleta = idBoleta;
    }

    public Item idBoleta(Boleta idBoleta) {
        setIdBoleta(idBoleta);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Item withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Item && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Item instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("descripcion", getDescripcion()) //
                .add("stock", getStock()) //
                .add("idBole", getIdBole()) //    
                .toString();
    }
}
